function [BW,maskedImage] = segmentImage(X,threashold, maskRadius)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 20-Mar-2019
%----------------------------------------------------


% Threshold image - manual threshold
BW = X > threashold;

% Open mask with disk
decomposition = 0;
se = strel('disk', maskRadius, decomposition);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

